server:  port: 8080

spring:
  jpa:
   hibernate:
    ddl-auto: update
  propierties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/products?zeroDateTimeBehaivor=convertToNull&serverTimezone=UTC
    username: root
    password: 140315pg